export const UPDATE_LAYOUTS = "UPDATE_LAYOUTS";
export const UPDATE_ACTIVE_LAYOUT = "UPDATE_ACTIVE_LAYOUT";
export const UPDATE_DRAGGED_IMAGE = "UPDATE_DRAGGED_IMAGE";
export const UPDATE_IMAGES = "UPDATE_IMAGES";
export const UPDATE_PRESETS = "UPDATE_PRESETS";
export const UPDATE_SELECTED_PRESET = "UPDATE_SELECTED_PRESET";